name: CI
on: [push, pull_request]

jobs:
  flake-check:
    runs-on: nixos
    steps:
      - uses: actions/checkout@v4
      - name: Nix Flake Check
        run: nix flake check --no-build

  build-marulk:
    runs-on: nixos
    needs: flake-check
    steps:
      - uses: actions/checkout@v4
      - name: Build marulk configuration
        run: nix build .#nixosConfigurations.marulk.config.system.build.toplevel
